"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SORTED_THREAT_SUMMARY_FIELDS = exports.CTI_ROW_RENDERER_FIELDS = exports.INDICATOR_REFERENCE = exports.INDICATOR_PROVIDER = exports.INDICATOR_LASTSEEN = exports.INDICATOR_FIRSTSEEN = exports.INDICATOR_EVENT_URL = exports.INDICATOR_DATASET = exports.FIRSTSEEN = exports.PROVIDER = exports.EVENT_REFERENCE = exports.EVENT_DATASET = exports.INDICATOR_MATCHED_TYPE = exports.INDICATOR_MATCHED_FIELD = exports.INDICATOR_MATCHED_ATOMIC = exports.INDICATOR_MATCH_SUBFIELDS = exports.MATCHED_TYPE = exports.MATCHED_FIELD = exports.MATCHED_ATOMIC = void 0;

var _constants = require("../constants");
/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */


const MATCHED_ATOMIC = 'matched.atomic';
exports.MATCHED_ATOMIC = MATCHED_ATOMIC;
const MATCHED_FIELD = 'matched.field';
exports.MATCHED_FIELD = MATCHED_FIELD;
const MATCHED_TYPE = 'matched.type';
exports.MATCHED_TYPE = MATCHED_TYPE;
const INDICATOR_MATCH_SUBFIELDS = [MATCHED_ATOMIC, MATCHED_FIELD, MATCHED_TYPE];
exports.INDICATOR_MATCH_SUBFIELDS = INDICATOR_MATCH_SUBFIELDS;
const INDICATOR_MATCHED_ATOMIC = `${_constants.INDICATOR_DESTINATION_PATH}.${MATCHED_ATOMIC}`;
exports.INDICATOR_MATCHED_ATOMIC = INDICATOR_MATCHED_ATOMIC;
const INDICATOR_MATCHED_FIELD = `${_constants.INDICATOR_DESTINATION_PATH}.${MATCHED_FIELD}`;
exports.INDICATOR_MATCHED_FIELD = INDICATOR_MATCHED_FIELD;
const INDICATOR_MATCHED_TYPE = `${_constants.INDICATOR_DESTINATION_PATH}.${MATCHED_TYPE}`;
exports.INDICATOR_MATCHED_TYPE = INDICATOR_MATCHED_TYPE;
const EVENT_DATASET = 'event.dataset';
exports.EVENT_DATASET = EVENT_DATASET;
const EVENT_REFERENCE = 'event.reference';
exports.EVENT_REFERENCE = EVENT_REFERENCE;
const PROVIDER = 'provider';
exports.PROVIDER = PROVIDER;
const FIRSTSEEN = 'first_seen';
exports.FIRSTSEEN = FIRSTSEEN;
const INDICATOR_DATASET = `${_constants.INDICATOR_DESTINATION_PATH}.${EVENT_DATASET}`;
exports.INDICATOR_DATASET = INDICATOR_DATASET;
const INDICATOR_EVENT_URL = `${_constants.INDICATOR_DESTINATION_PATH}.event.url`;
exports.INDICATOR_EVENT_URL = INDICATOR_EVENT_URL;
const INDICATOR_FIRSTSEEN = `${_constants.INDICATOR_DESTINATION_PATH}.${FIRSTSEEN}`;
exports.INDICATOR_FIRSTSEEN = INDICATOR_FIRSTSEEN;
const INDICATOR_LASTSEEN = `${_constants.INDICATOR_DESTINATION_PATH}.last_seen`;
exports.INDICATOR_LASTSEEN = INDICATOR_LASTSEEN;
const INDICATOR_PROVIDER = `${_constants.INDICATOR_DESTINATION_PATH}.${PROVIDER}`;
exports.INDICATOR_PROVIDER = INDICATOR_PROVIDER;
const INDICATOR_REFERENCE = `${_constants.INDICATOR_DESTINATION_PATH}.${EVENT_REFERENCE}`;
exports.INDICATOR_REFERENCE = INDICATOR_REFERENCE;
const CTI_ROW_RENDERER_FIELDS = [INDICATOR_MATCHED_ATOMIC, INDICATOR_MATCHED_FIELD, INDICATOR_MATCHED_TYPE, INDICATOR_DATASET, INDICATOR_REFERENCE, INDICATOR_PROVIDER];
exports.CTI_ROW_RENDERER_FIELDS = CTI_ROW_RENDERER_FIELDS;
const SORTED_THREAT_SUMMARY_FIELDS = [INDICATOR_MATCHED_FIELD, INDICATOR_MATCHED_TYPE, INDICATOR_PROVIDER, INDICATOR_FIRSTSEEN, INDICATOR_LASTSEEN];
exports.SORTED_THREAT_SUMMARY_FIELDS = SORTED_THREAT_SUMMARY_FIELDS;